// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbjwyungeyjknjrvqudy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiand5dW5nZXlqa25qcnZxdWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTExNTYsImV4cCI6MjA2ODU4NzE1Nn0.Wy4PTGhC3PO9DOllGY72wkH3PmhIX9UgQXynLuNIOPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});